name: '1'

on:
  push:

permissions:
  actions: write

jobs:
  initial-job:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Dispatch
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: '2-on-workflow-dispatch.yml',
              ref: 'main'
            })