name: '3a'

on:
  workflow_run:
    workflows: ['1']
    types: [completed]

jobs:
  post-push:
    runs-on: ubuntu-latest
    env:
      EVENT: "${{ github.event }}"
    steps:
      - run: echo $EVENT