on:
  workflow_run:
    workflows:
      - 1-on-push
    types:
      - completed

jobs:
  post-push:
    runs-on: ubuntu-latest
    env:
      EVENT: ${{ github.event }}
    steps:
      - run: echo $EVENT