on:
  workflow_run:
    workflows:
      - 2-on-workflow-dispatch.yml
    types:
      - completed

jobs:
  hello-world:
    runs-on: ubuntu-latest
    env:
      EVENT: ${{ github.event }}
    steps:
      - run: echo $EVENT